# Generated by Django 3.2.7 on 2021-09-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='slug',
            field=models.SlugField(default=12, max_length=250),
            preserve_default=False,
        ),
    ]
