# Generated by Django 3.2.7 on 2021-09-26 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_song_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='slug',
        ),
    ]
